AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/initializers/devise.rb'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140