[supervisord]
nodaemon=true
logfile=/app/log/supervisord.log
pidfile=/tmp/supervisord.pid

[program:cloudwatch-agent]
command=/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent
autostart=true
autorestart=true
startsecs=0
stderr_logfile=/app/log/cw-agent-error.log
stdout_logfile=/app/log/cw-agent.log
priority=1

[program:puma]
command=bundle exec puma -C config/puma.rb
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/log/error.log
stdout_logfile=/app/log/puma.log
priority=2
